### ISSUE TITLE
Crashing on Launch Android

### ISSUE THREAD

**Issue by NicholasFlamy** [immichFrame/ImmichFrame#150]
### Version

v1.0.13.0

### Deployment Method

Android

### Description

App crashes on launch.

Tested on Samsung Galaxy S22 OneUI 6.1 Android 14.

### Reproduction

Open the app.

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Should be fixed, sorry about that.

**Comment by NicholasFlamy** [comment]
You might wanna leave the issue open until you push a new release, that way if someone else goes to the issues about this they'll see it. (If you're literally about to push a release don't worry about it.)

**Comment by NicholasFlamy** [comment]
Oh, you update the apk in the release.

**Comment by NicholasFlamy** [comment]
Maybe you should add a note to the release about it.
