### ISSUE TITLE
APK issue on Firestick

### ISSUE THREAD

**Issue by PrzemekSkw** [immichFrame/ImmichFrame#152]
### Version

Last docker image

### Deployment Method

Docker on unraid

### Description

I sideload APK of immichframe to my fire stick 4k max. I install it but when I click some settings nothing happen. All settings are collapsed. Cannot be clicked and opened. First time I get lucky and when I just click save without any configuration I was able to put server IP:port and immich API. But then cannot use any options.

### Reproduction

Reinstall

### Expectations

Just work as it should.

### Logs

```shell
Now when I start app on fire stick I get error:
 not serialize the response body stream as System. Collections. Generic.ICollection'1
(ImmichFrame.Core.Api.AlbumResponseDto, ImmichFrame.Core, Version-1.0.0.0, Culture-neutral, PublicKeyToken-null)

Status:200
Response
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
ugh, same for Android TV. Nothing changed here other than the base Avalonia was updated and apparently broke this.

**Comment by JW-CH** [comment]
This is not the same issue! It clearly says that the response could not be parsed. @PrzemekSkw What server version are you on?

**Comment by PrzemekSkw** [comment]
> This is not the same issue! It clearly says that the response could not be parsed. @PrzemekSkw What server version are you on?

Hi, I have last docker: `ghcr.io/immichframe/immichframe:latest`.
But it looks like Android APK on Fire stick issue.
Regards.

**Comment by JW-CH** [comment]
Docker is for the web app, this has nothing to do with the apk (client app). The client app is not provided via docker.

But can you also check what version your immich Server is running? See here:
![image](https://github.com/user-attachments/assets/d6340a47-5458-4aab-8840-fb4ccaab76e5)

**Comment by PrzemekSkw** [comment]
> Docker is for the web app, this has nothing to do with the apk (client app). The client app is not provided via docker.
> 
> But can you also check what version your immich Server is running?

Hi, You ask about server version. I can tell You only that my server is installed with last docker image. I don't know where to find version.
APK I download from that githib releases page.
Regrds.

**Comment by 3rob3** [comment]
> This is not the same issue! It clearly says that the response could not be parsed. @PrzemekSkw What server version are you on?

What are you talking about? I was referring to this:
“All settings are collapsed. Cannot be clicked and opened.”

**Comment by PrzemekSkw** [comment]
> > This is not the same issue! It clearly says that the response could not be parsed. @PrzemekSkw What server version are you on?
> 
> What are you talking about? I was referring to this: “All settings are collapsed. Cannot be clicked and opened.” The other issue has got to be older server version.

That issue is only on tv. On tablet or smartphone app there's no problem. Do I need to run docker with different tag?

**Comment by 3rob3** [comment]
> > > This is not the same issue! It clearly says that the response could not be parsed. @PrzemekSkw What server version are you on?
> > 
> > 
> > What are you talking about? I was referring to this: “All settings are collapsed. Cannot be clicked and opened.” The other issue has got to be older server version.
> 
> That issue is only on tv. On tablet or smartphone app there's no problem. Do I need to run docker with different tag?

How did you enter your settings on TV if they are always collapsed? The only way I can is by using the restore button to load a previously saved config.

**Comment by PrzemekSkw** [comment]
> > > > This is not the same issue! It clearly says that the response could not be parsed. @PrzemekSkw What server version are you on?
> > > 
> > > 
> > > What are you talking about? I was referring to this: “All settings are collapsed. Cannot be clicked and opened.” The other issue has got to be older server version.
> > 
> > 
> > That issue is only on tv. On tablet or smartphone app there's no problem. Do I need to run docker with different tag?
> 
> How did you enter your settings on TV if they are always collapsed? The only way I can is by using the restore button to load a previously saved config.

When I install first time I get button to go to settings.

**Comment by 3rob3** [comment]
> > > > > This is not the same issue! It clearly says that the response could not be parsed. @PrzemekSkw What server version are you on?
> > > > 
> > > > 
> > > > What are you talking about? I was referring to this: “All settings are collapsed. Cannot be clicked and opened.” The other issue has got to be older server version.
> > > 
> > > 
> > > That issue is only on tv. On tablet or smartphone app there's no problem. Do I need to run docker with different tag?
> > 
> > 
> > How did you enter your settings on TV if they are always collapsed? The only way I can is by using the restore button to load a previously saved config.
> 
> When I install first time I get button to go to settings.

I meant how did you input the setting values if you all the fields are collapsed?

**Comment by 3rob3** [comment]
@JW-CH , rolling Avalonia nuget back to 11.2.0-beta1 fixes the issue (collapsed fields not expanding with remote). Not ideal since they have released beta2 and RC1 since.

**Comment by PrzemekSkw** [comment]
> I meant how did you input the setting values if you all the fields are collapsed?
When I cannot set any option when first time launch app I just click SAVE and then it shows me first settings fields: `Server URL:... and API Key:....`

**Comment by 3rob3** [comment]
> > I meant how did you input the setting values if you all the fields are collapsed?
> 
> When I cannot set any option when first time launch app I just click SAVE and then it shows me first settings fields: `Server URL:... and API Key:....`

Ah, ok.

**Comment by nebriv** [comment]
Also experiencing the same problem on the latest release v1.0.13.0. First time user - APK was side loaded, none of the settings can be opened.

**Comment by 3rob3** [comment]
Yes, issue was identified and will be fixed in next release by rolling back Avalonia versions. Hopefully today.

**Comment by PrzemekSkw** [comment]
> Yes, issue was identified and will be fixed in next release by rolling back Avalonia versions. Hopefully today.

Hi, thanks. Issue with collapsed options are fixed now but after I put my server, API and album guuid I get error like on photo.
![IMG_20241015_111540](https://github.com/user-attachments/assets/78df5faf-3659-44fa-979e-1c2cffcc258a)
