### ISSUE TITLE
Unraid Web App not loading settings.json

### ISSUE THREAD

**Issue by lajewishhome** [immichFrame/ImmichFrame#160]
### Version

v1.0.13.0

### Deployment Method

Unraid Docker install

### Description

I'm not able to get the Settings.json to load my font customization choices, and weather api.
I know the settings work, because the Windows desktop version works just fine.

### Reproduction

Install docker image from Unraid App Center.

### Expectations

I just want to have larger font, different color, and my weather api loaded

### Configuration

```xml
{
  "ImmichServerUrl": "my immich url",
  "ApiKey": "my api key",
  "ImageStretch": "Uniform",
  "Margin": "0,0,0,0",
  "Interval": 10,
  "TransitionDuration": 2,
  "DownloadImages": false,
  "ShowMemories": false,
  "RenewImagesDuration": 30,
  "Albums": [],
  "ExcludedAlbums": [],
  "People": [
    "my code for person1",
    "my code for person2"
  ],
  "RefreshAlbumPeopleInterval": 12,
  "ImmichFrameAlbumName": "",
  "ShowClock": true,
  "ClockFontSize": 36,
  "ClockFormat": "hh:mm:ss",
  "ShowPhotoDate": true,
  "PhotoDateFontSize": 36,
  "PhotoDateFormat": "MM-dd-yyyy",
  "ShowImageDesc": true,
  "ImageDescFontSize": 36,
  "ShowImageLocation": true,
  "ImageLocationFormat": "City,State,Country",
  "ImageLocationFontSize": 36,
  "FontColor": "#ffffff",
  "WeatherApiKey": "myapikey",
  "ShowWeatherDescription": true,
  "WeatherFontSize": 36,
  "UnitSystem": "imperial",
  "WeatherLatLong": "mylat/long",
  "Language": "en",
  "UnattendedMode": false
}
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
Hello @lajewishhome 

The Docker/Web version of immichFrame is not feature-complete. Regarding the weather: #157 is nearly done, this will display weather info. 

Many features are being implemented, but this takes some time, since this is a rewrite of the desktop version. Keep updating immichFrame and features will appear ;) Thank you for your patience.

**Comment by JW-CH** [comment]
#157 reintroduces weather. Will be included in the next release.
