### ISSUE TITLE
Display Memories in correct order

### ISSUE THREAD

**Issue by Borbosch** [immichFrame/ImmichFrame#163]
### Description

Me and my family love the Memory-Lane of immich. So this project was the right solution to get the Pictures of the past years on our Home-Tablet as a daily slide-show. 
For me it would be great to have the option that the memory-slide-show was shown in the correct order (a year ago, two years ago... and so on).
At the moment (with "Albums" empty and only `"ShowMemories": true`) it shows all photos in a random order.

### Use Case

The Use Case would resemble the Memory-Lane Feature of Immich itself.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
This makes sense, I agree.

**Comment by Borbosch** [comment]
Sorry if this is the wrong place and I may have to open a new issue, but with one of the latest releases the sorting has been lost again if i only have memories set up.

**Comment by 3rob3** [comment]
> Sorry if this is the wrong place and I may have to open a new issue, but with one of the latest releases the sorting has been lost again if i only have memories set up.

Memories is working correctly for me. What is happening for you?

**Comment by Borbosch** [comment]
Thanks for the fast reply.
With my docker-installation the slideshow jumps between "2 years ago" to "6 years ago" and the back to "2 years ago" and so on. In my log i don't see any way to debug this any further, so i thought i reply to this issue.

My Config looks like this:

``` json
{
  "ImmichServerUrl": "https://fotos.jankowskis.de",
  "ApiKey": "xxx",
  "ImageStretch": "Uniform",
  "Margin": "0,0,0,0",
  "Interval": 10,
  "TransitionDuration": 2,
  "DownloadImages": false,
  "ShowMemories": true,
  "RenewImagesDuration": 1,
  "RefreshAlbumPeopleInterval": 12,
  "ImmichFrameAlbumName": "",
  "ShowClock": true,
  "ClockFontSize": 18,
  "ClockFormat": "HH:mm",
  "ShowPhotoDate": true,
  "PhotoDateFontSize": 24,
  "PhotoDateFormat": "dd-MM-yyyy",
  "ShowImageDesc": true,
  "ImageDescFontSize": 24,
  "ShowImageLocation": true,
  "ImageLocationFormat": "City,State,Country",
  "ImageLocationFontSize": 16,
  "FontColor": "#FF5733",
  "WeatherApiKey": "",
  "ShowWeatherDescription": true,
  "WeatherFontSize": 24,
  "UnitSystem": "metric",
  "WeatherLatLong": "",
  "Language": "de",
  "UnattendedMode": false,
  "ImageZoom": true
}
```

**Comment by 3rob3** [comment]
you mean just two images? Are those the only memories you have from today maybe?

**Comment by Borbosch** [comment]
Sorry, that was just an example. 
It jumps wildly between the years and back again and shows other pictures of that day. I don't see a real pattern there.
And no, per year there are 6-10 Images to show. If i look at the memories in immich directly i can see that there are some videos in those groups, could that be a problem?

**Comment by Borbosch** [comment]
Sorry for beeing such a pain, but the problem still persists. I thought it was just the one Version that was "broken".
Is there some way i can debug this?

Here is my Config:

``` json
{
  "General": {
    "AuthenticationSecret": null,
    "PhotoDateFormat": "dd-MM-yyyy",
    "ImageLocationFormat": "City,State,Country",
    "UnitSystem": "metric",
    "Language": "de",
    "Interval": 10,
    "TransitionDuration": 2,
    "ShowClock": true,
    "ClockFormat": "hh:mm",
    "ShowProgressBar": true,
    "ShowPhotoDate": true,
    "ShowImageDesc": true,
    "ShowImageLocation": true,
    "ImageZoom": true,
    "ImagePan": false,
    "ImageFill": false,
    "Layout": "single"
  },
  "Accounts": [
    {
      "ImmichServerUrl": "https://fotos.xxx.local",
      "ApiKey": "xxx",
      "ShowMemories": true
    }
  ]
}

```

**Comment by 3rob3** [comment]
What is the issue, we have discussed a couple different things in this thread?

**Comment by Borbosch** [comment]
My only configured source of images are “Memories”.
When I look at the slideshow, all the images are displayed in a wild jumble.
Example:
First a picture from a year ago, then a picture from 13 years ago. Then another picture from 7 years ago and then again 2 pictures from a year ago.
My expectation would be that I first see all the pictures from a year ago, then from 2 years ago, then from 3 years ago up to 13 years ago.
In the end, each year as a block of pictures, just like the memory lane in the header of the Immich homepage.

The problem used to exist and the fix linked in this report also solved the problem, but since a few versions it is “broken” again.

**Comment by JW-CH** [comment]
> My only configured source of images are “Memories”. When I look at the slideshow, all the images are displayed in a wild jumble. Example: First a picture from a year ago, then a picture from 13 years ago. Then another picture from 7 years ago and then again 2 pictures from a year ago. My expectation would be that I first see all the pictures from a year ago, then from 2 years ago, then from 3 years ago up to 13 years ago. In the end, each year as a block of pictures, just like the memory lane in the header of the Immich homepage.
> 
> The problem used to exist and the fix linked in this report also solved the problem, but since a few versions it is “broken” again.

This may have got lost in the new implementation of @jpg0

**Comment by 3rob3** [comment]
@JW-CH , did we ever display them in order though? I don't recall that.

**Comment by Borbosch** [comment]
Pretty sure it did after  #178  was merged.

**Comment by 3rob3** [comment]
> Pretty sure it did after [#178](https://github.com/immichFrame/ImmichFrame/pull/178) was merged.

oops, totally missed/forgot about that. sorry.

**Comment by jpg0** [comment]
Yes, sorry, I assumed that everything was shuffled. What should be the behavior if, for example, show memories and show favorites is selected? Memories in order, favorites random order, then each shuffled into each other (but ordering for each preserved)?

**Comment by 3rob3** [comment]
Yeah it sounds like it. Memories in order, everything else random. I think you said same thing.
