### ISSUE TITLE
Arm64 Docker Build

### ISSUE THREAD

**Issue by mrjackwills** [immichFrame/ImmichFrame#166]
### Description

The current Docker images do not *appear* to work on Arm64 hardware

### Use Case

I currently run the ImmichFrame arm64 build on a Raspberry Pi 4. However, I would like to be able to run the Dockerized version, for both ease of use and easy up-gradability.

Running with the suggested docker-compose file on Arm64 hardware, the container just constantly restarts.

### Details

I am able to test on real hardware if needed.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
please try `ghcr.io/immichframe/immichframe:main`. you can use the `latest` tag next release.

**Comment by VenomousViper27** [comment]
Do you have any timeframe for when the next release will be available? I'm running into access denied errors when trying to pull main and install on rpi. Not a critical issue, but I can wait a bit if I can just pull the latest to install.

**Comment by JW-CH** [comment]
> Do you have any timeframe for when the next release will be available? I'm running into access denied errors when trying to pull main and install on rpi. Not a critical issue, but I can wait a bit if I can just pull the latest to install.

please don't pull main if you don't need to. use `latest` instead. I am currently testing stuff out with the docker builds. Sorry

**Comment by JW-CH** [comment]
I experienced this access denied error too. seems to be fixed as of now.

**Comment by JW-CH** [comment]
Should be fixed for `main`. Make sure you pull before running again.
