### ISSUE TITLE
Calendar overlay

### ISSUE THREAD

**Issue by DcryptedCA** [immichFrame/ImmichFrame#170]
### Description

Looking great so far!
Wondering if it would be possible to add in the ability to overlay a calendar from an ics file feed (URL). 

### Use Case

For larger displays this would allow users to display photos with the text calendar overlay. Alternatively, the calendar could go below to not be on top of the image, or on top with no background but the photo.

### Details

Options could include:
How many days to show
Background colors on individual event (light)
Event locations (at/in/none)
Event end time
Day x or Y label (for repeating events)
Font size
Current and future events only (hide items that are past)

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
Super interesing. I will have a look into it. You are using the Web (docker) version right?

**Comment by DcryptedCA** [comment]
Yes, running it as background/screensaver.

**Comment by JW-CH** [comment]
Working on it, backend works (with webcals). need to work on a good UI ;)
