### ISSUE TITLE
Discord link does not work

### ISSUE THREAD

**Issue by CodingEmil** [immichFrame/ImmichFrame#172]
### Version

X

### Deployment Method

X

### Description

The discord link on the readme page doesn't seem to be working. Discord can't find any channels.

### Reproduction

X

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by CodingEmil** [comment]
Just saw that it's not a discord server, it's a discord channel on the Immich server. One needs to join the Immich server first.
https://discord.immich.app/

**Comment by 3rob3** [comment]
> Just saw that it's not a discord server, it's a discord channel on the Immich server. One needs to join the Immich server first. https://discord.immich.app/

Beat me to it. Yes you need to join immich discord first, then it s a channel there.
