### ISSUE TITLE
Request: Option to add semi-transparent background to overlayed text

### ISSUE THREAD

**Issue by gabeklavans** [immichFrame/ImmichFrame#198]
### Description

It can be hard to ensure text like the clock and especially the metadata is legible against any photo. I suggest building in the option to have a semitransparent background behind whatever text elements are configured to increase legibility.

### Use Case

For when any overlayed text is configured that you want to ensure is always legible for a specific font color, regardless of the photo being displayed.

### Details

The color of the background could also be configurable, and the background could have a gradient fade into full transparency outside of the text regions.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by ScottFries** [comment]
Feel free to reference my change that applies this. Note that it's an issue I've still not found a happy-middle for. Regardless of settings I've tried, a static settings for font and background will always have cases where you will struggle to read the text (unless you go full opaque background, which is hideous). I think the real solution here is a dynamic setting for font based on image on display, which is certainly non-trivial and probably out of scope for this project.
https://github.com/immichFrame/ImmichFrame/commit/9b0ff90beacf06c01f8b1b749c4752a22c13cc57

**Comment by gabeklavans** [comment]
Thanks! I might check out your commit when I get a chance.

I agree that I don't think there will be a 100% solution within scope of this project. But what I'm envisioning seems pretty standard and will make things significantly more legible than they are now (I could totally just be naively optimistic here though).

**Comment by 3rob3** [comment]
Just an FYI, @ScottFries change is for the old, standalone, Avalonia version of the app. Not the new web based one.

@JW-CH's original web implementation had a semi transparent background for the text. I didn't really like it and requested we remove it. Maybe it can be optional setting?

**Comment by JW-CH** [comment]
> Just an FYI, @ScottFries change is for the old, standalone, Avalonia version of the app. Not the new web based one.
> 
> @JW-CH's original web implementation had a semi transparent background for the text. I didn't really like it and requested we remove it. Maybe it can be optional setting?

Sure, I can make a setting for it.

**Comment by iCanHazSkillz** [comment]
Instead of applying background to text, has it been considered to instead use the text-shadow CSS property? This would allow it to be seen on both light and dark colored images while remaining aesthetically pleasing.

CSS text-shadow Property:
    Syntax: text-shadow: x-offset y-offset blur-radius color;
    Example: text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); adds a soft black shadow.

**Comment by JW-CH** [comment]
> Instead of applying background to text, has it been considered to instead use the text-shadow CSS property? This would allow it to be seen on both light and dark colored images while remaining aesthetically pleasing.
> 
> CSS text-shadow Property: Syntax: text-shadow: x-offset y-offset blur-radius color; Example: text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); adds a soft black shadow.

I have played around with text shadows, but did not find it really pleasing or stand out. I'll check again with your values :)
