### ISSUE TITLE
Access ImmichFrame screensaver with Cloudflare

### ISSUE THREAD

**Issue by epkehab** [immichFrame/ImmichFrame#201]
### Description

ImmichFrame is behind Cloudflare / WARP and the android app and web is working perfectly (through bypass when WARP is used)! However, the screensaver is not working.  I probably need to add an exception to cloudflare in order to use this. Is there a specific  URL call made by the screensaver to the ImmichFrame server?

### Use Case

To be able to use ImmichFrame as screensaver remotely outside of own network

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
No, nothing special/different for screensaver. If you haven't already, can you verify it works using http://IP:port when you are on LAN?

**Comment by epkehab** [comment]
I was thinking too difficult. It was the device (Samsung telephone) that did not work with the app. It works on an android tablet.

**Comment by epkehab** [comment]
No issue, just device compatibility

**Comment by 3rob3** [comment]
> I was thinking too difficult. It was the device (Samsung telephone) that did not work with the app. It works on an android tablet.

Which Samsung phone? Surprised to hear it is not working on that.

**Comment by epkehab** [comment]
Samsung S23

**Comment by epkehab** [comment]
The screensaver does not work. The Immichframe app does work
