### ISSUE TITLE
Media Control for non touch screen Users

### ISSUE THREAD

**Issue by iCanHazSkillz** [immichFrame/ImmichFrame#219]
### Description

Having Immich-frame running on an RPI mounted on a monitor on the wall, there is currently no way for me to control my media on the fly. My current options are to either plug in a keyboard or remote to my RPI. Both of which involves having me right next to the RPI to perform any action.

Would it be possible to implement HTTP GET requests for these touchscreen buttons?

i.e. 
Go to previous picture:
http://[IP:Port]/command/?COMMAND=FRAMEPREV

Go to next picture:
http://[IP:Port]/command/?COMMAND=FRAMENEXT

Play/Pause:
http://[IP:Port]/command/?COMMAND=PLAYPAUSE

### Use Case

Control media playback for non-touch screen users.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
There are probably other easier ways too. All you need to do is trigger <, >, and space keyboard presses on the frame client. There ought to be other programs you can run on Pi for remote keyboard type of things.

**Comment by iCanHazSkillz** [comment]
Simulating a keyboard press is the easy part. Doing it remotely without any extra hardware is the challenge. If you have any other ideas beside my suggested http get request, I'm all ears.

**Comment by 3rob3** [comment]
Something like this? I'm not a python guy and this is all from GPT:
1. Install the pynput library:
pip install pynput
2. Create a Python script to handle key presses:
from flask import Flask, request
from pynput.keyboard import Key, Controller

app = Flask(__name__)
keyboard = Controller()

@app.route('/press', methods=['GET'])
def press_key():
    key = request.args.get('key')
    if key:
        if key.lower() == 'enter':
            keyboard.press(Key.enter)
            keyboard.release(Key.enter)
        else:
            keyboard.press(key)
            keyboard.release(key)
        return 'Key pressed: {}'.format(key)
    else:
        return 'Key not provided'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
3. Run the Python script:
python your_script_name.py
4. Send HTTP requests to trigger key presses:
You can now use tools like curl or a web browser to send requests to the Raspberry Pi and simulate key presses.
Example: To press the 'a' key:
Code

curl http://your_raspberry_pi_ip:5000/press?key=a
Example: To press the 'Enter' key:
Code

curl http://your_raspberry_pi_ip:5000/press?key=enter

**Comment by iCanHazSkillz** [comment]
Sounds more or less like the same idea- yeah. I ended up implementing the same thing but using httpout, pyautogui, and dockerizing the whole thing.

Feel free to check out my project if you'd like:
https://github.com/iCanHazSkillz/immichframe-remote

**Comment by 3rob3** [comment]
dang, your quick. Nice job!

**Comment by srvoets** [comment]
Any chance we can set the url with a curl command?  Typing in the URL on my shitty frameo device is incredibly annoying, it would be lovely to paste a url into a cmd to change it.

**Comment by 3rob3** [comment]
I used Adb input text for that:
Adb shell input text “TextToSend”
