### ISSUE TITLE
struggleling with "ImagesFromDate"

### ISSUE THREAD

**Issue by Dunkelschunkel** [immichFrame/ImmichFrame#221]
### Version

latest?

### Deployment Method

immich docker app unraid

### Description

No Assets found when using filter 
ImagesFromDate
ImagesUntilDate

I guess that it is only problem with formatting the values- The Settings.json as well as the env-file hove no example-values populated

### Reproduction

Using those field as variables when creating my docker image

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by Dunkelschunkel** [comment]
it should be noted to use the "mm.dd.yyyy", regardless from any date-settings for images. Furthermore, the option "ShowMemories" will prevent finding and displaying assets for the most parts

**Comment by JW-CH** [comment]
Can you post your config? Remove sensitive information.

**Comment by JW-CH** [comment]
Btw if you are not using settings, for example the `ImagesFromDate` and `ImagesUntilDate`, just remove them from your settings.

**Comment by JW-CH** [comment]
Should be fixed in the latest version.
