### ISSUE TITLE
BaseFontSize attribute doesn't change font size

### ISSUE THREAD

**Issue by iCanHazSkillz** [immichFrame/ImmichFrame#223]
### Version

V.1.0.20.0

### Deployment Method

Web

### Description

Settings.json file was modified to change the BaseFontSize in the following manner with no effect on text.

"BaseFontSize": "large",
"BaseFontSize": "34px",

None of the above have any effect on font size

Docker is pulling the latest image which should have this function implemented.
image: ghcr.io/immichframe/immichframe:v1.0.20.0

### Reproduction

Configure BaseFontSize withing the Settings.json file using the following declaration:
"BaseFontSize": "large",
"BaseFontSize": "34px",

Restarting the container will show no effect on font size.

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by iCanHazSkillz** [comment]
Converted my Settings.json to a .env file and issue persists unfortunately.

Attempted:
BaseFontSize=100px
BaseFontSize=large

None of the above have any effect on font size.

**Comment by 3rob3** [comment]
I have been sick all weekend. Feeling a little better so I’ll take  a look sometime today.

**Comment by iCanHazSkillz** [comment]
Hey take all the time you need to recoup. There's no rush to fix this.

Let me know if there's anything I can share to help troubleshoot further.

Appreciate you!

**Comment by iCanHazSkillz** [comment]
This is happening on browser

**Comment by 3rob3** [comment]
Working fine for me, are you refreshing your browser after making the change? I tried "xx-small" and "xx-large" and "16px" and all worked.
Are you ulling the right image?
image: ghcr.io/immichframe/immichframe:latest

**Comment by iCanHazSkillz** [comment]
Tried both latest and v.1.0.20.0
image: ghcr.io/immichframe/immichframe:latest
Image: ghcr.io/immichframe/immichframe:v1.0.20.0

I kill the chromium-browser on my rpi4 everytime a take the container down and put it back up

**Comment by 3rob3** [comment]
Have you tried checking it on a PC? I tried through PC and Android app. I did not try on a Pi.

**Comment by iCanHazSkillz** [comment]
Just tested and it works on PC.

RPI4 is running default Chromium 130.0.6723.116 built on Debian GNU/Linux 12 (bookworm)

**Comment by iCanHazSkillz** [comment]
Seems to be an isolated issue to Chromium on RPI

Ran it in Firefox-esr instead and font size works in there.

**Comment by 3rob3** [comment]
Can this be closed then?

**Comment by iCanHazSkillz** [comment]
I'll leave it up to you. The issue is technically still there, but at least there's a workaround - which is good. Ideally, the implementation of BaseFontSize should not be browser dependent.

**Comment by 3rob3** [comment]
I don't see same behavior on my Pi in Chromium. 
small:
![20241210_10h38m48s_grim](https://github.com/user-attachments/assets/77054dcd-f5a4-4932-a282-444f2726269e)
xx-large:
![20241210_10h37m04s_grim](https://github.com/user-attachments/assets/7c29a38c-3e86-40e3-9b71-5fdb5bc1b2ca)

**Comment by iCanHazSkillz** [comment]
Must be a me thing then 😁 

Let's close it off.
