### ISSUE TITLE
Reverse Proxy Configurations

### ISSUE THREAD

**Issue by dkedinger** [immichFrame/ImmichFrame#225]
### Description

I am trying to set this up so I can use NGINX proxy manager to have a reverse proxy point a URL with SSL to it. I would like to use this in a Home Assistant dashboard but can't without https.

### Use Case

Home Assistant dashboard in a webpage card

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
You should be able to configure that in NPM, no? I did the same for immich itself which doesn’t have https.

**Comment by JW-CH** [comment]
I am using NPM and configure like this:

![image](https://github.com/user-attachments/assets/381350d3-c366-4730-b429-ef7c93841b95)
![image](https://github.com/user-attachments/assets/9115448b-6faf-48cb-8a33-24495c8872dd)

**Comment by JW-CH** [comment]
Closed due to not directly related to ImmichFrame. Feel free to reopen.
