### ISSUE TITLE
immich frame android messes with default launcher settings

### ISSUE THREAD

**Issue by Dunkelschunkel** [immichFrame/ImmichFrame#226]
### Version

1.0.20.0

### Deployment Method

playstore google

### Description

the app, as beautiful as it is, it keeps messing up my default launcher settings. An Google tv the default launcher dialog keeps popping up an it does not matter if i only choose once or always - my lancher settings are not saved. 
On my phone i get notifications, that i have to set another launcher.
btw. Immich Frame does not show up as a launcher option - only the once that are already installed.
All the trouble vanishes upon uninstalling IF - which is what  I dont woant to  do

Dunkelschunkel 

### Reproduction

Install

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Weird, I do not see this behavior on my Google TV (Chromecast 4k). I can remove the HOME intent though (which is what is causing this I guess), that was added to support a device that didn't end up working anyway (Frameo Android photo frame).

**Comment by Blisterexe** [comment]
For my use on a tablet, it works perfectly, and no other solution would really work as well, given the tablet can struggle running the stock launcher and webview at the same time.

**Comment by Dunkelschunkel** [comment]
Maybe it is because i already use custom launchers.
On my Google TV there are two, next to the default one, which are emotn ui and custom launcher
On my smartphone I have the standard Xiaomi launcher and mlauncher.
Both devices show the same behavior.
Maybe this could be a suggestion for some further testing. But considering the lack of sleep and a short night ahead of me, I can only offer to test my theory tomorrow evening.
Please do not remove any intents just too quickly.

Dunkelschunkel

09.12.2024 21:45:31 Rob Rogers ***@***.***>:

**Comment by Dunkelschunkel** [comment]
Two images to give some more insight. 
The first show the launcher settings from the settings app, notice how Immichframe can be selected here 
The second is the dialogue popping up on pressing the home button. Notice the absence of immichframe. 
Maybe there is another intent missing that would fix the missing app
![Screenshot_2024-12-10-06-36-51-205_com android settings](https://github.com/user-attachments/assets/e9a65353-563a-48ed-8484-df827a0f28bc)

![Screenshot_2024-12-10-06-34-45-923_android](https://github.com/user-attachments/assets/7ed170ff-ee00-44be-b41d-470b3487130a)


 dunkelschunkel

**Comment by 3rob3** [comment]
You don't want to set ImmichFrame as your launcher (unless you know what your doing). This is for very niche devices so that they boot right into ImmichFrame. Is the issue that selecting 'Auswahl merken' doesn't work and it keeps asking every time Home button is pressed?

**Comment by 3rob3** [comment]
Can this be closed?

**Comment by Blisterexe** [comment]
i would note that setting it as a launcher is also very useful for turning an old tablet into a frame

**Comment by 3rob3** [comment]
I'm going to close this as I've not heard of any other complaints. @Dunkelschunkel , please feel free to re-open or resubmit if you disagree or have an issue.

**Comment by Dunkelschunkel** [comment]
Funny thing is, my custom phone launcher keeps nagging me to set it as the default launcher for as long as I have immichframe installed. As soon as I uninstall IF the reminder disappears. 
![Screenshot_2024-12-16-06-32-48-713_app mlauncher_1](https://github.com/user-attachments/assets/a90401b4-1450-41e7-ad15-6635f0ac243b)
