### ISSUE TITLE
Android app not working anymore

### ISSUE THREAD

**Issue by Tsamsiyu1** [immichFrame/ImmichFrame#243]
### Version

latest

### Deployment Method

Android

### Description

yesterday everything worked. today it did the update and i get this:
![WhatsApp Bild 2024-12-26 um 14 34 10_8d25a0fe](https://github.com/user-attachments/assets/2f7e3759-8ce2-41de-969a-7c92b9a0bce3)
i cant go to the settings like before. (they are the same settings as in the env in the docker web version)
Now it only gives me the setting to set the ImmichFrame server URL. 
those ImmichFrames are at my grandmoms houses and i do not want to expose all the images of my baby girl to the internet. which i would have to do to get it working with the docker server.
before the app was its own server.

### Reproduction

open the android app i tried it on 3 different devices

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
You probably updated the latest version of the app that requires a docker container to run. As of now, you could just install the old version of the immichFrame app and have everything working like before. The "old" app is discontinued, and we won't update it anymore, so when immich has a breaking change that changes the way the API works, the app will not work anymore. You have the option to connect that tablet via VPN (like tailscale, it is really easy) to the docker running in your home and not have to expose it to the internet. 

You can find the old app here: https://github.com/immichFrame/ImmichFrame/releases/tag/v1.0.16.0

**Comment by Tsamsiyu1** [comment]
thanks.
but what is the point of the app then? the browser does the same thing.

**Comment by JW-CH** [comment]
The app provides additional functionality like screensaver etc. also there is a "lite" mode for devices that are not too powerful like frameo frames. But you are right, the app is basicially just a brower that talks to the webpage. But that is basicially the whole point of it. This way, we can easily update and make use of browser technology without having to worry about different clients. So many devices support just a browser and that makes immichFrame available to all of them.

**Comment by bestrocker221** [comment]
I unfortunately updated the app to find out the same, which makes it is useless now.
Before you could just add all the settings in it and it would run without issues.. especially without requiring another back-end container (which is not the official immich).

PS: I loved the previous version, it was just perfect, so I am grateful for that.

**Comment by 3rob3** [comment]
> I unfortunately updated the app to find out the same, which makes it is useless now. Before you could just add all the settings in it and it would run without issues.. especially without requiring another back-end container (which is not the official immich).
> 
> PS: I loved the previous version, it was just perfect, so I am grateful for that.

As mentioned above, you can still run the version you are happy with, I don't think there have been any breaking changes:
https://github.com/immichFrame/ImmichFrame/releases/tag/v1.0.16.0

**Comment by Tsamsiyu1** [comment]
don't worry i coded my own android app that does the same thing as immichFrame and doesnt need a server. it uses the  immich api in a secure way without and keeps everything it shows on the device itself. You can set the refresh time, the time how often it connects to the server and fetches the new images to download and you can even set times for the background light of the device to turn off and on again. it shows time, date and the how many images are downloaded and on wich one the slideshow is. the only thing it does not do is blend the images into each other.
I wont publish it to the playstore since it costs money to do so but i can publish it on Github if you want

**Comment by 3rob3** [comment]
No thanks. I vastly prefer having the "work" done on the backend, especially using these low powered Frameo devices now almost exclusively.

**Comment by Tsamsiyu1** [comment]
i bought a 40€ android tablet that can handle this with almost no  CPU usage at all. but be my friend use whatever suits you better. I was just offering. If you don't need it its fine too
