### ISSUE TITLE
Photos from Specific Month

### ISSUE THREAD

**Issue by auntphil** [immichFrame/ImmichFrame#40]
I would love to show all photos from a specific month and all previous years.

Example:
The current month is March. The slide show should include photos from March 2024, March 2023, March 2022, etc...

**Comment by 3rob3** [comment]
That is an interesting idea. I wonder if others would want day or week as well.

**Comment by abe-101** [comment]
I would also want by year,

or on a slightly different note I would want to show photos from a time range

**Comment by 3rob3** [comment]
> I would also want by year,
> 
> or on a slightly different note I would want to show photos from a time range

I know it’s not ideal, but you can do this with albums.

**Comment by abe-101** [comment]
I was thinking of that
The only thing missing is newly added photos

I would like to be able to specify the frame to play from 2021 to present - this way it would include all newly added photos
