### ISSUE TITLE
Feature: Show two portrait photos side-by-side

### ISSUE THREAD

**Issue by 3rob3** [immichFrame/ImmichFrame#46]
Add a setting for optionally displaying two portrait photos next to each other.

**Comment by OliverLippertVw** [comment]
Same applies for landscape images, if you have a portrait monitor :)

**Comment by JW-CH** [comment]
First draft for portrait photos on a landscape monitor #173

**Comment by JW-CH** [comment]
Closed with #173 open new issues for missing functionalityl please :)
